import 'dotenv/config';
import fs from 'fs';
import { Pool } from 'pg';
import { PaceV2FactRow, fingerprintPaceV2FactRows } from '../src/etl/pace-v2-identity-repair';
import { fingerprintDriverIds, PaceV2IncompleteRebuildArtifact, PaceV2IncompleteRebuildManifest, parsePaceV2IncompleteRebuildArtifact, parsePaceV2IncompleteRebuildManifest, PACE_V2_INCOMPLETE_REBUILD_ID, rebuildFactsByRound } from '../src/etl/pace-v2-incomplete-rebuild';
interface Client { query<Row extends Record<string, unknown> = Record<string, unknown>>(sql: string, params?: unknown[]): Promise<{ rows: Row[] }>; release(): void }
interface QueryPool { connect(): Promise<Client>; end(): Promise<void> }
const asFact = (row: Record<string, unknown>): PaceV2FactRow => ({ ...row, season: Number(row.season), round: Number(row.round), track_id: String(row.track_id), driver_id: String(row.driver_id), session_type: String(row.session_type), lap_number: Number(row.lap_number), stint_id: Number(row.stint_id), stint_lap_index: Number(row.stint_lap_index), lap_time_seconds: row.lap_time_seconds === null ? null : Number(row.lap_time_seconds), is_valid_lap: Boolean(row.is_valid_lap), is_pit_lap: Boolean(row.is_pit_lap), is_out_lap: Boolean(row.is_out_lap), is_in_lap: Boolean(row.is_in_lap), clean_air_flag: Boolean(row.clean_air_flag), compound: row.compound === null ? null : String(row.compound), tyre_age_laps: row.tyre_age_laps === null ? null : Number(row.tyre_age_laps), methodology_version: String(row.methodology_version) });
export async function runPaceV2IncompleteRebuild(pool: QueryPool, manifest: PaceV2IncompleteRebuildManifest, artifact: PaceV2IncompleteRebuildArtifact) {
 const client = await pool.connect(); try { await client.query('BEGIN ISOLATION LEVEL SERIALIZABLE'); await client.query("SELECT set_config('statement_timeout', $1, true)", ['5000ms']);
  const relations = await client.query("SELECT to_regclass('pace_v2_lap_rebuild')::text AS relation UNION ALL SELECT to_regclass('pace_v2_rebuild_audit')::text AS relation"); if (relations.rows.length !== 2 || relations.rows.some((row) => !row.relation)) throw new Error('FAIL_CLOSED: reviewed incomplete rebuild migration is missing');
  const triggers = await client.query("SELECT COUNT(*) = 3 AS enabled FROM pg_trigger WHERE tgrelid IN ('pace_v2_lap_rebuild'::regclass, 'pace_v2_rebuild_audit'::regclass) AND tgname IN ('pace_v2_lap_rebuild_immutable', 'pace_v2_rebuild_audit_immutable', 'pace_v2_lap_rebuild_no_insert_after_approval') AND tgenabled <> 'D'"); if (!triggers.rows[0]?.enabled) throw new Error('FAIL_CLOSED: incomplete rebuild immutability triggers are unavailable');
  for (const entry of manifest.rounds) { const original = (await client.query('SELECT season, round, track_id, driver_id, session_type, lap_number, stint_id, stint_lap_index, lap_time_seconds, is_valid_lap, is_pit_lap, is_out_lap, is_in_lap, clean_air_flag, compound, tyre_age_laps, methodology_version FROM laps_normalized_v2 WHERE season=2026 AND round=$1 AND session_type=\'R\' FOR SHARE', [entry.round])).rows.map(asFact); const canonical = await client.query('SELECT DISTINCT rd.driver_id FROM race r JOIN race_data rd ON rd.race_id=r.id AND LOWER(rd.type) IN (\'race\', \'race_result\') WHERE r.year=2026 AND r.round=$1', [entry.round]); const replacement = rebuildFactsByRound(artifact.facts).get(entry.round) ?? [];
   if (original.length !== entry.original_fact_row_count || fingerprintPaceV2FactRows(original) !== entry.original_fact_fingerprint || fingerprintDriverIds(canonical.rows.map((row) => String(row.driver_id))) !== entry.canonical_driver_fingerprint || canonical.rows.length !== entry.canonical_driver_count || new Set(replacement.map((row) => row.driver_id)).size !== entry.canonical_driver_count || replacement.some((row) => !canonical.rows.some((item) => String(item.driver_id) === row.driver_id))) throw new Error(`FAIL_CLOSED: incomplete rebuild provenance disagrees for round ${entry.round}`);
   const existing = await client.query('SELECT 1 FROM pace_v2_rebuild_audit WHERE rebuild_version=$1 AND season=2026 AND round=$2 AND session_type=\'R\'', [PACE_V2_INCOMPLETE_REBUILD_ID, entry.round]); if (existing.rows.length) throw new Error(`FAIL_CLOSED: incomplete rebuild audit already exists for round ${entry.round}`);
   const values = replacement.flatMap((r) => [PACE_V2_INCOMPLETE_REBUILD_ID, r.season,r.round,r.track_id,r.driver_id,r.session_type,r.lap_number,r.stint_id,r.stint_lap_index,r.lap_time_seconds,r.is_valid_lap,r.is_pit_lap,r.is_out_lap,r.is_in_lap,r.clean_air_flag,r.compound,r.tyre_age_laps,r.methodology_version]); const placeholders = replacement.map((_, i) => `(${Array.from({ length: 18 }, (_, c) => `$${i * 18 + c + 1}`).join(',')})`).join(','); await client.query(`INSERT INTO pace_v2_lap_rebuild (rebuild_version,season,round,track_id,driver_id,session_type,lap_number,stint_id,stint_lap_index,lap_time_seconds,is_valid_lap,is_pit_lap,is_out_lap,is_in_lap,clean_air_flag,compound,tyre_age_laps,methodology_version) VALUES ${placeholders}`, values); await client.query('INSERT INTO pace_v2_rebuild_audit (rebuild_version,season,round,session_type,rebuild_manifest_fingerprint,identity_map_fingerprint,original_fact_fingerprint,replacement_fact_fingerprint,original_fact_row_count,replacement_fact_row_count,canonical_driver_fingerprint,canonical_driver_count,methodology_version) VALUES ($1,2026,$2,\'R\',$3,$4,$5,$6,$7,$8,$9,$10,$11)', [PACE_V2_INCOMPLETE_REBUILD_ID,entry.round,manifest.manifest_fingerprint,artifact.identity_map_fingerprint,entry.original_fact_fingerprint,fingerprintPaceV2FactRows(replacement),entry.original_fact_row_count,replacement.length,entry.canonical_driver_fingerprint,entry.canonical_driver_count,manifest.methodology_version]); }
  await client.query('COMMIT'); return { rebuilt_rounds: manifest.rounds.length, rebuild_fact_rows: artifact.facts.length };
 } catch (error) { await client.query('ROLLBACK').catch(() => undefined); throw error; } finally { client.release(); } }
function configuration(env: NodeJS.ProcessEnv = process.env): string { if (env.PACE_V2_INCOMPLETE_REBUILD_ENABLED !== 'true' || env.PACE_V2_INCOMPLETE_REBUILD_TARGET !== 'primary' || !env.DATABASE_URL) throw new Error('FAIL_CLOSED: explicit primary rebuild configuration is required'); return env.DATABASE_URL; }
if (require.main === module) { try { const args=process.argv.slice(2); if(args.length!==4||args[0]!=='--manifest'||args[2]!=='--facts') throw new Error(); const pool=new Pool({connectionString:configuration(),ssl:{rejectUnauthorized:false},max:1}); runPaceV2IncompleteRebuild(pool,parsePaceV2IncompleteRebuildManifest(JSON.parse(fs.readFileSync(args[1],'utf8'))),parsePaceV2IncompleteRebuildArtifact(JSON.parse(fs.readFileSync(args[3],'utf8')))).then((value)=>process.stdout.write(`${JSON.stringify(value)}\n`)).catch(()=>{process.stdout.write('{"status":"refused","error":"pace_v2_incomplete_rebuild_failed"}\n');process.exitCode=1;}).finally(()=>pool.end()); } catch { process.stdout.write('{"status":"refused","error":"pace_v2_incomplete_rebuild_failed"}\n'); process.exitCode=1; } }
